CREATE DATABASE TODOList_db;
USE TODOList_db;

CREATE TABLE list
(
	id int NOT NULL AUTO_INCREMENT,
	thingsTODO varchar(255) NOT NULL,
	isDone BOOLEAN DEFAULT 0,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);